/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package telas;

import apoio.ComboItem;
import apoio.Mensagem;
import controladores.ControlaPokemons;
import controladores.ControlaTipos;
import entidades.DAO.CombosDAO;
import entidades.Pokemons;
import entidades.Tipos;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author belli
 */
public class TelaPokemons extends javax.swing.JInternalFrame {

    ControlaPokemons cp = new ControlaPokemons();
    ControlaTipos ct = new ControlaTipos();
    int codigo = 0;

    /**
     * Creates new form TelaPokemons
     */
    public TelaPokemons() {
        initComponents();
        montaTabela();
        new CombosDAO().popularCombo("tipos", cmbTiposprim);
        new CombosDAO().popularCombo("tipos", cmbTipossecun);
    }

    public boolean validaCampos() {
        if (txtNome.getText().trim().isEmpty()
                || cmbTiposprim.getSelectedIndex() == -1) {
            Mensagem.erro("um ou mais campos não pode ser nulo");
            return false;
        }
        return true;
    }

    private void montaTabela() {
        ArrayList<Pokemons> p = cp.recuperarTodos();
        if (p == null) {
            System.out.println("Ocorreu um erro ao consultar as tarefas");
        } else {
            tblPokemons.setModel(new AbstractTableModel() {
                @Override
                public String getColumnName(int column) {
                    switch (column) {
                        case 0:
                            return "Num Pokedex";
                        case 1:
                            return "Nome";
                        case 2:
                            return "Tipo Primario";
                        case 3:
                            return "Tipo Secundario";
                        default:
                            return "";
                    }
                }

                @Override
                public int getColumnCount() {
                    return 4;
                }

                @Override
                public int getRowCount() {
                    return p.size();
                }

                @Override
                public Object getValueAt(int rowIndex, int columnIndex) {
                    Pokemons ps = p.get(rowIndex);

                    if (p != null) {
                        switch (columnIndex) {
                            case 0:
                                return ps.getNumPokedex();
                            case 1:
                                return ps.getNome();
                            case 2:
                                Tipos t = ct.recuperarUm(ps.getTipoPrimario());
                                return t.getNome();
                            case 3:
                                Tipos t2 = ct.recuperarUm(ps.getTipoSecundario());
                                if (t2 != null) {
                                    return t2.getNome();
                                }
                                return "-";
                        }
                    }

                    return "n/d";
                }
            });

            tblPokemons.getColumnModel().getColumn(0).setMinWidth(80);
            tblPokemons.getColumnModel().getColumn(0).setPreferredWidth(80);
            tblPokemons.getColumnModel().getColumn(0).setMaxWidth(20);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabAbas = new javax.swing.JTabbedPane();
        panConsulta = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPokemons = new javax.swing.JTable();
        btnExcluir = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        panCadastra = new javax.swing.JPanel();
        btnSalvar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblTipo1 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        cmbTiposprim = new javax.swing.JComboBox<>();
        lblTipo2 = new javax.swing.JLabel();
        cmbTipossecun = new javax.swing.JComboBox<>();

        setClosable(true);

        tblPokemons.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblPokemons);

        btnExcluir.setBackground(new java.awt.Color(255, 153, 153));
        btnExcluir.setForeground(new java.awt.Color(0, 255, 204));
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(this::btnExcluirActionPerformed);

        btnEditar.setText("Editar");
        btnEditar.addActionListener(this::btnEditarActionPerformed);

        javax.swing.GroupLayout panConsultaLayout = new javax.swing.GroupLayout(panConsulta);
        panConsulta.setLayout(panConsultaLayout);
        panConsultaLayout.setHorizontalGroup(
            panConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panConsultaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE))
            .addGroup(panConsultaLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btnExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEditar)
                .addGap(22, 22, 22))
        );
        panConsultaLayout.setVerticalGroup(
            panConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panConsultaLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExcluir)
                    .addComponent(btnEditar))
                .addContainerGap())
        );

        tabAbas.addTab("Consulta", panConsulta);

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(this::btnSalvarActionPerformed);

        jLabel2.setText("Nome do Pokemon");

        lblTipo1.setText("Tipo primário");

        txtNome.addActionListener(this::txtNomeActionPerformed);

        cmbTiposprim.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblTipo2.setText("Tipo secundário");

        cmbTipossecun.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbTipossecun.addActionListener(this::cmbTipossecunActionPerformed);

        javax.swing.GroupLayout panCadastraLayout = new javax.swing.GroupLayout(panCadastra);
        panCadastra.setLayout(panCadastraLayout);
        panCadastraLayout.setHorizontalGroup(
            panCadastraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panCadastraLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap(556, Short.MAX_VALUE))
            .addGroup(panCadastraLayout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panCadastraLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(panCadastraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTipo1)
                    .addComponent(cmbTiposprim, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panCadastraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panCadastraLayout.createSequentialGroup()
                        .addGroup(panCadastraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(228, 228, 228))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panCadastraLayout.createSequentialGroup()
                        .addGroup(panCadastraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cmbTipossecun, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTipo2))
                        .addGap(55, 55, 55))))
        );
        panCadastraLayout.setVerticalGroup(
            panCadastraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCadastraLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(panCadastraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panCadastraLayout.createSequentialGroup()
                        .addGroup(panCadastraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lblTipo2))
                        .addGap(9, 9, 9)
                        .addGroup(panCadastraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbTipossecun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panCadastraLayout.createSequentialGroup()
                        .addComponent(lblTipo1)
                        .addGap(9, 9, 9)
                        .addComponent(cmbTiposprim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        tabAbas.addTab("Cadastra", panCadastra);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabAbas, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabAbas)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if (!validaCampos()) {
            return;
        }
        String nome = txtNome.getText();
        ComboItem tipoPrimario = (ComboItem) cmbTiposprim.getSelectedItem();
        ComboItem tipoSecundario = (ComboItem) cmbTipossecun.getSelectedItem();

        Pokemons p = new Pokemons();
        p.setNome(nome);
        p.setTipoPrimario(tipoPrimario.getCodigo());
        if (tipoSecundario != null) {
            p.setTipoSecundario(tipoSecundario.getCodigo());
        } else {
            p.setTipoSecundario(0);
        }
        boolean retorno = false;
        if (codigo == 0) {
            retorno = cp.salvar(p);
        } else {
            p.setNumPokedex(codigo);
            retorno = cp.editar(p);
        }

        if (retorno) {
            if (codigo == 0) {
                Mensagem.informacao("Salvo com sucesso");
            } else {
                codigo = 0;
                JOptionPane.showMessageDialog(null, "Editado com sucesso");
            }

            txtNome.setText("");
            cmbTiposprim.setSelectedIndex(-1);
            cmbTipossecun.setSelectedIndex(-1);

            txtNome.requestFocus();
            montaTabela();
        } else {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro, verifique os logs.");
        }

    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        String idString = String.valueOf(tblPokemons.getValueAt(tblPokemons.getSelectedRow(), 0));
        int id = Integer.parseInt(idString);

        boolean retorno = cp.excluir(id);
        if (retorno) {
            JOptionPane.showMessageDialog(null, "Registro excluído com sucesso!");
            montaTabela();
        } else {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro ao excluir!");
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void cmbTipossecunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipossecunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTipossecunActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        String idString = String.valueOf(tblPokemons.getValueAt(tblPokemons.getSelectedRow(), 0));
        int id = Integer.parseInt(idString);

        Pokemons p = cp.recuperarUm(id);
        if (p != null) {
            codigo = p.getNumPokedex();
            txtNome.setText(p.getNome());
            ComboItem tipoPrimario = (ComboItem) cmbTiposprim.getSelectedItem();
            ComboItem tipoSecundario = (ComboItem) cmbTipossecun.getSelectedItem();
            tabAbas.setSelectedIndex(1);
        } else {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro ao editar!");
        }   // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cmbTiposprim;
    private javax.swing.JComboBox<String> cmbTipossecun;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTipo1;
    private javax.swing.JLabel lblTipo2;
    private javax.swing.JPanel panCadastra;
    private javax.swing.JPanel panConsulta;
    private javax.swing.JTabbedPane tabAbas;
    private javax.swing.JTable tblPokemons;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
