/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package telas;

import apoio.ComboItem;
import controladores.ControlaPokemons;
import controladores.ControlaTipos;
import entidades.DAO.CombosDAO;
import entidades.Pokemons;
import entidades.Tipos;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author belli
 */
public class TelaPokemons extends javax.swing.JInternalFrame {

    ControlaPokemons cp = new ControlaPokemons();
    ControlaTipos ct = new ControlaTipos();

    /**
     * Creates new form TelaPokemons
     */
    public TelaPokemons() {
        initComponents();
        montaTabela();
        new CombosDAO().popularCombo("tipos", cmbTiposprim);
        new CombosDAO().popularCombo("tipos", cmbTipossecun);
    }

    private void montaTabela() {
        ArrayList<Pokemons> p = cp.recuperarTodos();
        if (p == null) {
            System.out.println("Ocorreu um erro ao consultar as tarefas");
        } else {
            tblPokemons.setModel(new AbstractTableModel() {
                @Override
                public String getColumnName(int column) {
                    switch (column) {
                        case 0:
                            return "Num Pokedex";
                        case 1:
                            return "Nome";
                        case 2:
                            return "Tipo Primario";
                        case 3:
                            return "Tipo Secundario";
                        default:
                            return "";
                    }
                }

                @Override
                public int getColumnCount() {
                    return 4;
                }

                @Override
                public int getRowCount() {
                    return p.size();
                }

                @Override
                public Object getValueAt(int rowIndex, int columnIndex) {
                    Pokemons ps = p.get(rowIndex);

                    if (p != null) {
                        switch (columnIndex) {
                            case 0:
                                return ps.getNumPokedex();
                            case 1:
                                return ps.getNome();
                            case 2:
                                Tipos t = ct.recuperarUm(ps.getTipoPrimario());
                                return t.getNome();
                            case 3:
                                return ps.getTipoSecundario();
                        }

                    }

                    return "n/d";
                }
            });

            tblPokemons.getColumnModel().getColumn(0).setMinWidth(80);
            tblPokemons.getColumnModel().getColumn(0).setPreferredWidth(80);
            tblPokemons.getColumnModel().getColumn(0).setMaxWidth(20);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        panConsulta = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPokemons = new javax.swing.JTable();
        btnExcluir = new javax.swing.JButton();
        panCadastra = new javax.swing.JPanel();
        btnSalvar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblTipo1 = new javax.swing.JLabel();
        txtNomePoke = new javax.swing.JTextField();
        cmbTiposprim = new javax.swing.JComboBox<>();
        lblTipo2 = new javax.swing.JLabel();
        cmbTipossecun = new javax.swing.JComboBox<>();

        setClosable(true);

        tblPokemons.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblPokemons);

        btnExcluir.setBackground(new java.awt.Color(255, 153, 153));
        btnExcluir.setForeground(new java.awt.Color(0, 255, 204));
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(this::btnExcluirActionPerformed);

        javax.swing.GroupLayout panConsultaLayout = new javax.swing.GroupLayout(panConsulta);
        panConsulta.setLayout(panConsultaLayout);
        panConsultaLayout.setHorizontalGroup(
            panConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panConsultaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panConsultaLayout.createSequentialGroup()
                .addContainerGap(145, Short.MAX_VALUE)
                .addComponent(btnExcluir)
                .addGap(139, 139, 139))
        );
        panConsultaLayout.setVerticalGroup(
            panConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panConsultaLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExcluir)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Consulta", panConsulta);

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(this::btnSalvarActionPerformed);

        jLabel2.setText("Nome do Pokemon");

        lblTipo1.setText("Tipo primário");

        txtNomePoke.addActionListener(this::txtNomePokeActionPerformed);

        cmbTiposprim.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblTipo2.setText("Tipo secundário");

        cmbTipossecun.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout panCadastraLayout = new javax.swing.GroupLayout(panCadastra);
        panCadastra.setLayout(panCadastraLayout);
        panCadastraLayout.setHorizontalGroup(
            panCadastraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCadastraLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panCadastraLayout.createSequentialGroup()
                .addContainerGap(125, Short.MAX_VALUE)
                .addGroup(panCadastraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panCadastraLayout.createSequentialGroup()
                        .addGroup(panCadastraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNomePoke, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(116, 116, 116))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panCadastraLayout.createSequentialGroup()
                        .addGroup(panCadastraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTipo2)
                            .addComponent(cmbTiposprim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTipo1)
                            .addComponent(btnSalvar)
                            .addComponent(cmbTipossecun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(121, 121, 121))))
        );
        panCadastraLayout.setVerticalGroup(
            panCadastraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panCadastraLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomePoke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(lblTipo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbTiposprim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTipo2)
                .addGroup(panCadastraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panCadastraLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel3))
                    .addGroup(panCadastraLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbTipossecun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(btnSalvar)
                .addGap(30, 30, 30))
        );

        jTabbedPane1.addTab("Cadastra", panCadastra);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomePokeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomePokeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomePokeActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        String nome = txtNomePoke.getText();
        ComboItem tipoPrimario = (ComboItem) cmbTiposprim.getSelectedItem();
        ComboItem tipoSecundario = (ComboItem) cmbTipossecun.getSelectedItem();

        Pokemons p = new Pokemons();
        p.setNome(nome);
        p.setTipoPrimario(tipoPrimario.getCodigo());
        p.setTipoSecundario(tipoSecundario.getCodigo());
        boolean retorno = cp.salvar(p);

        if (retorno) {
            JOptionPane.showMessageDialog(null, "Salvo com sucesso");
            txtNomePoke.setText("");
            txtNomePoke.requestFocus();
            montaTabela();
        } else {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro, verifique os logs.");
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        String idString = String.valueOf(tblPokemons.getValueAt(tblPokemons.getSelectedRow(), 0));
        int id = Integer.parseInt(idString);

        boolean retorno = cp.excluir(id);
        if (retorno) {
            JOptionPane.showMessageDialog(null, "Registro excluído com sucesso!");
            montaTabela();
        } else {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro ao excluir!");
        }
    }//GEN-LAST:event_btnExcluirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cmbTiposprim;
    private javax.swing.JComboBox<String> cmbTipossecun;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblTipo1;
    private javax.swing.JLabel lblTipo2;
    private javax.swing.JPanel panCadastra;
    private javax.swing.JPanel panConsulta;
    private javax.swing.JTable tblPokemons;
    private javax.swing.JTextField txtNomePoke;
    // End of variables declaration//GEN-END:variables
}
