package telas;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import telas.TelaTipos;

/**
 *
 * @author belli
 */
public class TelaPokedex extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaPokedex.class.getName());
    private TelaTipos tt;
    private TelaTreinadores tn;
    private TelaPokemons tp;
    private TelaItensBolsa tib;

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPokedex() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu4 = new javax.swing.JMenu();
        dskPainel = new javax.swing.JDesktopPane();
        menuTelas = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuTipos = new javax.swing.JMenuItem();
        menuTreinadores = new javax.swing.JMenuItem();
        menuPokemons = new javax.swing.JMenuItem();
        menuItens = new javax.swing.JMenuItem();

        jMenu4.setText("jMenu4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 0, 0));

        dskPainel.setBackground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout dskPainelLayout = new javax.swing.GroupLayout(dskPainel);
        dskPainel.setLayout(dskPainelLayout);
        dskPainelLayout.setHorizontalGroup(
            dskPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 773, Short.MAX_VALUE)
        );
        dskPainelLayout.setVerticalGroup(
            dskPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 502, Short.MAX_VALUE)
        );

        jMenu1.setText("Telas");

        menuTipos.setText("Tipos");
        menuTipos.addActionListener(this::menuTiposActionPerformed);
        jMenu1.add(menuTipos);

        menuTreinadores.setText("Treinadores");
        menuTreinadores.addActionListener(this::menuTreinadoresActionPerformed);
        jMenu1.add(menuTreinadores);

        menuPokemons.setText("Pokemons");
        menuPokemons.addActionListener(this::menuPokemonsActionPerformed);
        jMenu1.add(menuPokemons);

        menuItens.setText("Itens da Bolsa");
        menuItens.addActionListener(this::menuItensActionPerformed);
        jMenu1.add(menuItens);

        menuTelas.add(jMenu1);

        setJMenuBar(menuTelas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dskPainel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dskPainel)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuTiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTiposActionPerformed
        if (tt == null || tt.isClosed()) {
            tt = new TelaTipos();
            dskPainel.add(tt);
            tt.setVisible(true);
        }
    }//GEN-LAST:event_menuTiposActionPerformed

    private void menuTreinadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTreinadoresActionPerformed
        if (tn == null || tn.isClosed()) {
            tn = new TelaTreinadores();
            dskPainel.add(tn);
            tn.setVisible(true);
    }//GEN-LAST:event_menuTreinadoresActionPerformed
    }
    private void menuPokemonsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPokemonsActionPerformed
        if (tp == null || tp.isClosed()) {
            tp = new TelaPokemons();
            dskPainel.add(tp);
            tp.setVisible(true);
        }
    }//GEN-LAST:event_menuPokemonsActionPerformed

    private void menuItensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItensActionPerformed
        if (tib == null || tib.isClosed()) {
            tib = new TelaItensBolsa();
            dskPainel.add(tib);
            tib.setVisible(true);
    }//GEN-LAST:event_menuItensActionPerformed
    }
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaPokedex().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dskPainel;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuItem menuItens;
    private javax.swing.JMenuItem menuPokemons;
    private javax.swing.JMenuBar menuTelas;
    private javax.swing.JMenuItem menuTipos;
    private javax.swing.JMenuItem menuTreinadores;
    // End of variables declaration//GEN-END:variables
}
